# from api.serializers.DashboardSerializer import
from api.serializers.gateway.login_serializer import LoginSerializer
from api.serializers.gateway.register_serializer import RegisterSerializer
from api.serializers.pm.fishingspot_serializer import FishingSpotSerializer
from api.serializers.pm.pm_serializer import SearchElementSerializer
from api.serializers.homepage.homepage_serializer import UserLocationSerializer
from api.serializers.pm.favorites_serializer import FavoritesSerializer
