# Generated by Django 2.2.7 on 2020-01-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserLocation',
        ),
    ]
