# Generated by Django 2.2.7 on 2020-01-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20200107_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchelement',
            old_name='FishingSpot',
            new_name='fishingSpot',
        ),
    ]
